# Generated by Django 3.0.5 on 2020-09-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(max_length=10, verbose_name='DNI')),
                ('nacionalidad', models.BooleanField(verbose_name='Nacionalidad')),
                ('edad', models.BooleanField(verbose_name='Edad')),
                ('telefono', models.IntegerField(max_length=15, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('consulta', models.BooleanField(verbose_name='Consulta')),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
    ]
